---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: common-mtls-dr
spec:
  exportTo:
    - .
  host: '*.svc.cluster.local'
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
