---
kind: Secret
apiVersion: v1
metadata:
  name: istio-egressgateway-certs
stringData:
  tls.crt: |-
    {{ index .Values.certs.elastic "tls.crt" | nindent 4 }}
  tls.key: |-
    {{ index .Values.certs.elastic "tls.key" | nindent 4 }}
type: kubernetes.io/tls
