---
kind: Service
apiVersion: v1
metadata:
  name: ingressgateway
  labels:
    app: ingressgateway
spec:
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8443
  type: ClusterIP
  selector:
    app: ingressgateway