---
kind: Secret
apiVersion: v1
metadata:
  name: ingressgateway-certs-secret
stringData:
  tls.crt: |-
    {{ index .Values.certs.ingress "tls.crt" | nindent 4 }}
  tls.key: |-
    {{ index .Values.certs.ingress "tls.key" | nindent 4 }}
  ca.crt: |-
    {{ index .Values.certs.common "ca.crt" | nindent 4 }}
type: Opaque
