---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak
stringData:
  KC_DB_URL_HOST: {{ .Values.keycloak.database.host }}
  KC_DB_URL_PORT: {{ .Values.keycloak.database.port | quote }}
  KC_DB_URL_DATABASE: {{ .Values.keycloak.database.name }}
  KC_DB: postgres
  KC_DB_USERNAME: {{ .Values.keycloak.database.user }}
  KC_DB_PASSWORD: {{ .Values.keycloak.database.password }}
  KC_DB_SCHEMA: {{ .Values.keycloak.database.schema }}
  KC_HTTP_ENABLED: 'false'
  KC_HOSTNAME_STRICT_HTTPS: 'false'
  KC_HOSTNAME_STRICT: 'false'
  KEYCLOAK_ADMIN: {{ .Values.keycloak.admin.user }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.keycloak.admin.password }}
  KC_AUTO_BUILD: 'false'
  KC_HTTP_PORT: '8080'
  KC_LOG_LEVEL: INFO
  KC_PROXY: edge
  KC_IMPORT_REALM: 'true'
  KC_HTTP_RELATIVE_PATH: /auth
  KC_HOSTNAME_ADMIN_URL: 'https://{{ .Values.keycloak.host }}/auth/'
  KC_HTTPS_CERTIFICATE_FILE: /etc/x509/https/tls.crt
  KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/x509/https/tls.key
---
apiVersion: v1
kind: Secret
metadata:
  name: certs-keycloak
type: Opaque
stringData:
  tls.crt: |-
    {{ index .Values.certs.keycloak "tls.crt" | nindent 4 }}
  tls.key: |-
    {{ index .Values.certs.keycloak "tls.key" | nindent 4 }}
  ca.crt: |-
    {{ index .Values.certs.common "ca.crt" | nindent 4 }}