---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: postgres-internal-dr
spec:
  exportTo:
    - .
  host: postgres-egress-service
  subsets:
    - name: postgres-internal
