---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: webapp-gw
spec:
  selector:
    app: ingressgateway
  servers:
    - hosts:
        - {{ .Values.internal.webapp.host }}
      port:
        name: https
        number: 8443
        protocol: HTTPS
      tls:
        caCertificates: /secrets/istio/ingressgateway-certs/ca.crt
        mode: MUTUAL
        privateKey: /secrets/istio/ingressgateway-certs/tls.key
        serverCertificate: /secrets/istio/ingressgateway-certs/tls.crt