---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: 'true'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '30'
    nginx.ingress.kubernetes.io/proxy-buffers-number: '8'
    nginx.ingress.kubernetes.io/proxy-connect-timeout: '30'
    nginx.ingress.kubernetes.io/client-body-buffer-size: 16M
    nginx.ingress.kubernetes.io/proxy-read-timeout: '30'
    nginx.ingress.kubernetes.io/proxy-body-size: 64k
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  name: webapp
  labels:
    app: webapp
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.internal.webapp.host }}
      secretName: ingressgateway-certs-secret
  rules:
    - host: {{ .Values.internal.webapp.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ingressgateway
                port:
                  number: 443